"""
LiveConfigPatcher — patches strategy YAML dict for live execution context.

The strategy YAML was generated by the backtester and contains paths to
parquet files that do not exist in the live context (or are irrelevant).
This patcher adjusts only what is necessary to make StrategyConfig.from_dict()
succeed and produce a config that reflects live execution.

What is patched:
  - data.paths.strategy_ohlcv  → sentinel dummy path (pipeline bypassed)
  - data.paths.htf_ohlcv       → sentinel dummy path (pipeline bypassed)
  - data.paths.artf_ohlcv      → real path from BrokerSupportConfig.live_data
  - data.paths.ltf_ohlcv       → None (LTF not fetched live)
  - data.date_range            → None (no date filtering on live data)
  - execution.mode             → 'core' (no analytics overhead in live loop)
  - output.reports.enabled     → False (no HTML report generation live)

What is NOT patched (strategy signal logic — must be backtested values):
  - filters.*                  → all filter params and sequence unchanged
  - trade_management.*         → SL/TP/ATR/spread params unchanged
  - asset.*                    → symbol + pip/point size unchanged

Architecture note:
  The DataLoader is NOT called in live context. DataBundle is built directly
  by LiveDataBundle from fetched DataFrames. StrategyConfig is patched so that
  SignalGenerator, FilterPipeline, and RiskManager can all be instantiated
  from it with correct parameters.
"""
from __future__ import annotations

import copy
from pathlib import Path
from typing import Any, Dict

import yaml
from loguru import logger

from src.broker_support.config.broker_support_config import BrokerSupportConfig

# Sentinel path used for strategy_ohlcv and htf_ohlcv in patched config.
# These fields are required by StrategyConfig schema but are never read
# in live context — DataBundle is built from live-fetched DataFrames.
# The file must exist on disk for StrategyConfig validation to pass.
# We use the artf file as the sentinel since it always exists.
_SENTINEL_COMMENT = "LIVE_SENTINEL"


class LiveConfigPatcher:
    """
    Produces a patched strategy config dict suitable for live paper trading.

    Usage:
        patcher = LiveConfigPatcher(bs_config)
        patched_dict = patcher.patch(raw_strategy_dict)
        strategy_config = StrategyConfig.from_dict(patched_dict)
    """

    def __init__(self, bs_config: BrokerSupportConfig) -> None:
        self._bs = bs_config

    def patch(self, raw_strategy_dict: Dict[str, Any]) -> Dict[str, Any]:
        """
        Patch strategy YAML dict for live context.

        Args:
            raw_strategy_dict: dict from yaml.safe_load(strategy_yaml).

        Returns:
            Deep copy with live-context overrides applied.
            Original dict is never mutated.
        """
        d = copy.deepcopy(raw_strategy_dict)

        artf_path_str = str(self._bs.live_data.artf_ohlcv_path)

        # ── data.paths overrides ──────────────────────────────────────────
        # strategy_ohlcv and htf_ohlcv must point to existing files to pass
        # StrategyConfig.from_dict() validation. We use the artf parquet as
        # a sentinel — it always exists and is never read in live context.
        # DataBundle bypasses DataLoader entirely.
        d.setdefault("data", {}).setdefault("paths", {})
        d["data"]["paths"]["strategy_ohlcv"] = artf_path_str  # sentinel
        d["data"]["paths"]["htf_ohlcv"]      = artf_path_str  # sentinel
        d["data"]["paths"]["artf_ohlcv"]     = artf_path_str  # real — used by RiskManager
        d["data"]["paths"]["ltf_ohlcv"]      = None           # LTF not fetched live

        # ── data.date_range → None ────────────────────────────────────────
        # No date filtering on live DataBundle. Live DataFrames cover only
        # the fetched window and must be used as-is.
        d["data"]["date_range"] = None

        # ── execution.mode → core ─────────────────────────────────────────
        # No analytics overhead in live loop. Core mode = fastest path.
        d.setdefault("execution", {})["mode"] = "core"

        # ── output.reports.enabled → False ────────────────────────────────
        # No HTML reports in live context.
        d.setdefault("output", {}).setdefault("reports", {})["enabled"] = False

        logger.debug(
            "LiveConfigPatcher: patched strategy config for live context. "
            f"artf_path={artf_path_str}, mode=core, date_range=None, reports=False"
        )
        return d

    @classmethod
    def load_and_patch(
        cls,
        bs_config: BrokerSupportConfig,
    ) -> Dict[str, Any]:
        """
        Convenience: load strategy YAML from BrokerSupportConfig and patch.

        Returns patched dict ready for StrategyConfig.from_dict().

        Raises:
            FileNotFoundError: if strategy YAML path does not exist.
            yaml.YAMLError:    if YAML is malformed.
        """
        yaml_path = bs_config.strategy.yaml_path
        if not yaml_path.exists():
            raise FileNotFoundError(
                f"Strategy YAML not found: {yaml_path}"
            )
        with open(yaml_path, "r") as f:
            raw = yaml.safe_load(f)

        logger.info(f"LiveConfigPatcher: loaded strategy YAML from {yaml_path}")
        patcher = cls(bs_config)
        return patcher.patch(raw)
